import type { CSSProperties } from 'react';
import { modernTheme as m } from './theme';

/** Modern template styles (inline CSSProperties; spec §7.1 subset — flexbox only). */
export const styles: Record<string, CSSProperties> = {
  page: {
    fontFamily: 'Inter',
    backgroundColor: m.pageBg,
    color: m.text,
    fontSize: 11,
    lineHeight: 1.45,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  sidebar: {
    width: '34%',
    backgroundColor: m.accent,
    color: m.sidebarText,
    padding: '28px 18px',
    display: 'flex',
    flexDirection: 'column',
  },
  main: {
    width: '66%',
    padding: '28px 24px',
    display: 'flex',
    flexDirection: 'column',
  },
  avatarWrap: { display: 'flex', flexDirection: 'row', justifyContent: 'center', marginBottom: 12 },
  avatar: { width: 92, height: 92, borderRadius: 46, objectFit: 'cover' },
  avatarFallback: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: m.accentDark,
    color: m.sidebarText,
    fontSize: 30,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideName: { fontSize: 18, fontWeight: 700, textAlign: 'center', color: m.sidebarText },
  sideHeadline: { fontSize: 11, textAlign: 'center', color: m.sidebarMuted, marginTop: 2, marginBottom: 8 },
  sideSection: { marginTop: 12, display: 'flex', flexDirection: 'column' },
  sideTitle: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: m.sidebarText,
    borderBottom: `1px solid ${m.barTrack}`,
    paddingBottom: 3,
    marginBottom: 6,
  },
  sideItem: { fontSize: 10, color: m.sidebarMuted, marginBottom: 3 },
  barLabel: { fontSize: 10, color: m.sidebarText, marginBottom: 2, marginTop: 5 },
  barTrack: { width: '100%', height: 5, backgroundColor: m.barTrack, borderRadius: 3 },
  barFill: { height: 5, backgroundColor: m.barFill, borderRadius: 3 },
  section: { marginBottom: 12, display: 'flex', flexDirection: 'column' },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: m.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    borderBottom: `2px solid ${m.rule}`,
    paddingBottom: 3,
    marginBottom: 7,
  },
  paragraph: { fontSize: 11, color: m.text, margin: 0 },
  entry: { marginBottom: 9, display: 'flex', flexDirection: 'column' },
  entryTitle: { fontSize: 11.5, fontWeight: 600, color: m.heading },
  entryMeta: { fontSize: 10, color: m.faint, marginTop: 1 },
  entryDesc: { fontSize: 10.5, color: m.muted, marginTop: 3 },
  bulletList: { marginTop: 3, marginBottom: 0, paddingLeft: 16 },
  bulletItem: { fontSize: 10.5, color: m.muted, marginBottom: 1 },
  link: { color: m.sidebarMuted, textDecoration: 'none' },
  mainLink: { color: m.accent, textDecoration: 'none' },
};
